// TODO: UPDATE nav each week

export const navigation = [
  {
    title: 'Articles about learning English',
    links: [{ title: 'All articles', href: '/articles' }],
  },
  {
    title: 'Upper Intermediate',
    links: [
      { title: 'Week 1: Relationships', href: '/upper/week01' },
      { title: 'Week 2: Storytelling', href: '/upper/week02' },
      { title: 'Week 3: Science and Tech', href: '/upper/week03' },
      { title: 'Week 4: Art and Creativity', href: '/upper/week04' },
      { title: 'Week 5: Development', href: '/upper/week05' },
      { title: 'Week 6: Alternative Travel', href: '/upper/week06' },
      { title: 'Week 7: Customs and Behaviour', href: '/upper/week07' },
      { title: 'Week 8: Hopes and Ambitions', href: '/upper/week08' },
      { title: 'Week 9: The News', href: '/upper/week09' },
      { title: 'Week 10: Talented People', href: '/upper/week10' },
      { title: 'Week 11: Knowledge and Learning', href: '/upper/week11' },
      { title: 'Week 12: Money', href: '/upper/week12' },
    ],
  },
  {
    title: 'Intermediate',
    links: [
      // { title: 'Week 1', href: '/int/week01' },
      // { title: 'Week 2', href: '/int/week02' },
      // { title: 'Week 3', href: '/int/week03' },
      { title: 'Week 4: Jobs', href: '/int/week04' },
      // { title: 'Week 5', href: '/int/week05' },
      // { title: 'Week 6', href: '/int/week06' },
      // { title: 'Week 7', href: '/int/week07' },
      // { title: 'Week 8', href: '/int/week08' },
      // { title: 'Week 9', href: '/int/week09' },
      // { title: 'Week 10', href: '/int/week10' },
      // { title: 'Week 11', href: '/int/week11' },
      // { title: 'Week 12', href: '/int/week12' },
    ],
  },
  // {
  //   title: 'Pre-Intermediate',
  //   links: [
  //     { title: 'Week 1', href: '/preint/week01' },
  //     { title: 'Week 2', href: '/preint/week02' },
  //     { title: 'Week 3', href: '/preint/week03' },
  //     { title: 'Week 4', href: '/preint/week04' },
  //     { title: 'Week 5', href: '/preint/week05' },
  //     { title: 'Week 6', href: '/preint/week06' },
  //     { title: 'Week 7', href: '/preint/week07' },
  //     { title: 'Week 8', href: '/preint/week08' },
  //     { title: 'Week 9', href: '/preint/week09' },
  //     { title: 'Week 10', href: '/preint/week10' },
  //     { title: 'Week 11', href: '/preint/week11' },
  //     { title: 'Week 12', href: '/preint/week12' },
  //   ],
  // },
  // {
  //   title: 'Elementary',
  //   links: [
  //     { title: 'Week 1', href: '/elem/week01' },
  //     { title: 'Week 2', href: '/elem/week02' },
  //     { title: 'Week 3', href: '/elem/week03' },
  //     { title: 'Week 4', href: '/elem/week04' },
  //     { title: 'Week 5', href: '/elem/week05' },
  //     { title: 'Week 6', href: '/elem/week06' },
  //     { title: 'Week 7', href: '/elem/week07' },
  //     { title: 'Week 8', href: '/elem/week08' },
  //     { title: 'Week 9', href: '/elem/week09' },
  //     { title: 'Week 10', href: '/elem/week10' },
  //     { title: 'Week 11', href: '/elem/week11' },
  //     { title: 'Week 12', href: '/elem/week12' },
  //   ],
  // },
  // {
  //   title: 'Beginner',
  //   links: [
  //     { title: 'Week 1', href: '/beginner/week01' },
  //     { title: 'Week 2', href: '/beginner/week02' },
  //     { title: 'Week 3', href: '/beginner/week03' },
  //     { title: 'Week 4', href: '/beginner/week04' },
  //     { title: 'Week 5', href: '/beginner/week05' },
  //     { title: 'Week 6', href: '/beginner/week06' },
  //     { title: 'Week 7', href: '/beginner/week07' },
  //     { title: 'Week 8', href: '/beginner/week08' },
  //     { title: 'Week 9', href: '/beginner/week09' },
  //     { title: 'Week 10', href: '/beginner/week10' },
  //     { title: 'Week 11', href: '/beginner/week11' },
  //     { title: 'Week 12', href: '/beginner/week12' },
  //   ],
  // },
]
